name: nhentai
description: nhentai

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.2
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  marquee: ^2.2.0
  visibility_detector: ^0.2.0
  scroll_to_index: ^2.1.0
  flutter_bloc: ^7.3.1
  shared_preferences: ^2.0.8
  flutter_staggered_grid_view: ^0.4.1
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0
  path_provider: ^2.0.7
  percent_indicator: ^3.4.0
  share: ^2.0.4
  package_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.17
  scrollable_positioned_list: ^0.2.3
  flutter_linkify: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  flutter_launcher_icons: "^0.9.2"
  sqflite:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/ic_lang_jp.png
   - images/ic_lang_gb.png
   - images/ic_lang_cn.png
   - images/ic_nhentai_logo.svg
   - images/ic_nothing_here_grey.png
   - images/ic_loading_cat_transparent.gif
   - images/ic_un_seen.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans_Bold
      fonts:
        - asset: fonts/NotoSans_Bold.ttf

    - family: NotoSans_BoldItalic
      fonts:
        - asset: fonts/NotoSans_BoldItalic.ttf

    - family: NotoSans_Italic
      fonts:
        - asset: fonts/NotoSans_Italic.ttf

    - family: NotoSans_Regular
      fonts:
        - asset: fonts/NotoSans_Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
